### ISSUE TITLE
How to make tsParticles full width and height of a container and not the whole page?

### ISSUE THREAD

**Issue by lloydjatkinson** [tsparticles/tsparticles#1277]
I have been struggling trying to get particles.js to be the background of a given element. That library seems to position the canvas weirdly and it always makes the canvas wider and longer than the element, and hacking around with `top` and `left` doesn't really work well either. As far as I can tell it assumes you only ever want the whole page background to be it's canvas. so I decided to look into tsParticles.

Does tsParticles properly support working with an arbitrary element and it's width and height, e.g. it would use these values to create the canvas correctly? If the div is 100px wide and 100px in height, the canvas would be 100px wide and 100px in height.

For example, I have a div in the center. I'd like tsParticles to render only **_inside_** the div and **_underneath_** the text:

![image](https://user-images.githubusercontent.com/5633938/106393585-dd88dd80-63ef-11eb-95d2-da8212da87fb.png)

Would it be possible to get an example of this?

**Comment by matteobruni** [comment]
Hi @lloydjatkinson,

Yes, this configuration is possible. You can see that working in these samples

https://codepen.io/matteobruni/pen/XWjLOpQ

https://codepen.io/matteobruni/pen/QWKXPRq

I try to explain how to achieve it.

```javascript
tsParticles.load('your-div-id', { /* your configuration */ }); // or loadJSON if you are using an external JSON file
```

Don't enable `backgroundMode` options or use any kind of fixed CSS on that div.

The best result will be achieved using a container for particles and your content like this:

```html
<div id="container">
    <div id="tsparticles"></div>
    <div id="your-div"></div>
</div>
```

```css
#container {
    position: relative
}

#tsparticles {
    position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    padding: 0;
    margin: 0;
    z-index: 0; /* if you use -1 you have to set to `"window"` the interactivity.detectsOn property */
}

#your-div {
    position: absolute;
    top: 0;
    left: 0;
    z-index: 1;
}
```

Hope it helps, if you need more help don't hesitate to ask

**Comment by hartmutobendorf** [comment]
Thank you, brilliant tip!

**Comment by jwandekoken** [comment]
How to achieve that with "react-tsparticles"?

**Comment by matteobruni** [comment]
> How to achieve that with "react-tsparticles"?

Starting from 1.37.0 the `fullScreen` option is enabled by default, you can disable it and follow the instructions described above

**Comment by SuperWoll** [comment]
Is it possible to eloborate a little more on how to get particles only to work on a spesific seciton of the page? i am using react-tsparticles. Been stuck for 2 days now, trying to figure it out...

**Comment by matteobruni** [comment]
> Is it possible to eloborate a little more on how to get particles only to work on a spesific seciton of the page? i am using react-tsparticles. Been stuck for 2 days now, trying to figure it out...

I've created a sample to show just the differences here: https://codepen.io/matteobruni/pen/BawqaxW

I'll explain below more in details:

**Full Screen**

It's the standard behavior, if you load a standard tsParticles config without specifying any `fullScreen` options they are going to be the website background with `fixed` position and `z-index: 0`.

*HTML*

``` html
<div id="tsparticles-full"></div>
```

*CSS*

``` css
/* No custom CSS needed */
```

*JavaScript*

``` javascript
tsParticles.load("tsparticles-full", { /* options here */ });
```

**Custom Positioning**

This is achieved disabling the `fullScreen` options, you must handle the positioning yourself.

*HTML*

``` html
<div id="tsparticles-custom"></div>
```

*CSS*

``` css
/* this creates a 200x200 pixels square in the middle of the page containing the particles, you need to create your own CSS to position the particles where you need them */
#tsparticles-custom {
  position: absolute;
  left: calc(50% - 100px);
  top: calc(50% - 100px);
  margin: 0;
  padding: 0;
  width: 200px;
  height: 200px;
  z-index: 10;
}
```

*JavaScript*

``` javascript
tsParticles.load("tsparticles-custom", {
  fullScreen: {
    enable: false
  },
  /* all other options */
});
```
