### ISSUE TITLE
Page flashes on reload or when using forward/back buttons

### ISSUE THREAD

**Issue by adamalston** [tsparticles/tsparticles#1378]
**Which version are you using?**
Switched over from [`react-particles-js`](https://github.com/Wufe/react-particles-js) to [`react-tsparticles`](https://github.com/matteobruni/tsparticles)
Version: 1.20.1

**Is the latest version affected?** Yes.

*You can checkout latest version [here](https://www.npmjs.com/package/tsparticles)*

- [x] Yes
- [ ] No

**Which library are you using?**

- [x] React (`react-tsparticles`)

<details>
 <summary><b>tsParticles Configuration</b></summary>
  
  ```javascript
        particles: {
            number: {
                value: 100,
                density: {
                    enable: true,
                    area: 800,
                },
            },
            color: {
                value: ["C912ED", "00BFFF", "22DD22", "FFD500", "FF8000", "FF2600"],
            },
            shape: {
                type: "circle",
                stroke: {
                    width: 0,
                    color: "000000",
                },
                polygon: {
                    nb_sides: 5,
                },
                image: {
                    src: "img/github.svg",
                    width: 100,
                    height: 100,
                },
            },
            opacity: {
                value: 0.9,
                random: false,
                anim: {
                    enable: false,
                    speed: 1,
                    opacity_min: 0.5,
                    sync: false,
                },
            },
            size: {
                value: 4,
                random: {
                    enable: true,
                    minimumValue: 2,
                },
                anim: {
                    enable: false,
                    speed: 30,
                    size_min: 0.1,
                    sync: true,
                },
            },
            links: {
                enable: true,
                distance: 75,
                color: "808080",
                opacity: 0.9,
                width: 1,
                consent: false,
                blink: false,
            },
            move: {
                enable: true,
                speed: 4,
                direction: "none",
                random: false,
                straight: false,
                out_mode: "bounce",
                bounce: false,
                attract: {
                    enable: false,
                    rotateX: 600,
                    rotateY: 1200,
                },
            },
        },
        interactivity: {
            detect_on: "canvas",
            events: {
                onhover: {
                    enable: true,
                    mode: "repulse",
                },
                onclick: {
                    enable: true,
                    mode: "push",
                },
                resize: true,
            },
            modes: {
                attract: {
                    distance: 100,
                    duration: 1,
                    speed: 5,
                },
                bubble: {
                    distance: 400,
                    size: 40,
                    duration: 2,
                    opacity: 8,
                    speed: 3,
                },
                grab: {
                    distance: 400,
                    line_linked: {
                        opacity: 1,
                    },
                },
                push: {
                    particles_nb: 3,
                },
                remove: {
                    particles_nb: 2,
                },
                repulse: {
                    distance: 100,
                    duration: 1,
                },
            },
        },
        retina_detect: true,
  ```
</details>

**Describe the bug**
I deployed a test build of my website (https://604ebdb6cfdb60890449804e--adamalston.netlify.app/) updated with the `react-tsparticles` package and I have noticed when reloading that the page flashes. This issue was not present before changing packages 

**To Reproduce**
1. Go to a test build of my website from an hour ago (https://604ebdb6cfdb60890449804e--adamalston.netlify.app/) . This page was built using `react-tsparticles`.
2. Make sure the page is in dark mode (black background) -> Refresh the page -> The screen flashes

**Expected behavior**
1. Go to a test build of my website (https://60157ee5cb006f54ea89b6ca--adamalston.netlify.app/) from January. This page was built using `react-particles-js`.
2. Make sure the page is in dark mode (black background) -> Refresh the page -> The screen flashes

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 89.0.x.x

**Additional context**
The only thing that has changes between the two deploys is the package used.

**Comment by matteobruni** [comment]
Hi @adamalston,

I noticed also a different `.particles` CSS:

Original:

```css
.particles {
    transition: background-color .5s linear;
    position: absolute;
    background-color: #fff;
    background-color: var(--primaryBackgroundColor);
    background-repeat: no-repeat;
    background-size: cover;
    background-position: 50% 50%;
    z-index: 0
}
```

New Version

```css
.particles {
    background-color: 0; /* this is added */
    transition: background-color .5s linear;
    position: absolute;
    background-color: #fff;
    background-color: var(--primaryBackgroundColor);
    background-repeat: no-repeat;
    background-size: cover;
    background-position: 50% 50%;
    z-index: 0
}
```

I tried your configuration and you don't set the background color using the `tsParticles` options `background` property so it must be a CSS related issue.
